# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Production

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::136827333458:role/KMarchant-GitHub-Deployment
        aws-region: us-east-2
    - name: Deploy
      env:
          SOURCE_DIR: '/home/runner/work/kmarchant-blazor/kmarchant-blazor/bin/Release/net6.0/publish/wwwroot'
          AWS_REGION: 'ap-southeast-2'
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      run: |
        aws s3 sync ${SOURCE_DIR} s3://${AWS_S3_BUCKET} \
              --acl public-read \
              --region ${AWS_REGION} \
              --no-progress \
              --delete
